//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquaBilling_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderT
    {
        public int Order_id { get; set; }
        public int Consumer_id { get; set; }
        public string Supplier_Name { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public string Address { get; set; }
        public string Order_Status { get; set; }
    
        public virtual Consumer Consumer { get; set; }
    }
}
