//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquaBilling_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Supplier_id { get; set; }
        public string Supplier_Name { get; set; }
        public string Category { get; set; }
        public string Address { get; set; }
        public int Available_Quantity_in_ltr_ { get; set; }
        public int Rate_per_ltr { get; set; }
        public string Contact_No { get; set; }
        public string Password { get; set; }
    }
}
